#!/usr/bin/env python3

import sys
import os
import blessed
import subprocess
import getpass
import time

### My Modules
lib_path = os.path.abspath(os.path.join(os.path.dirname(__file__), './modules')) # Define absolut path to custom modules

sys.path.append(lib_path)

# text_justify_center, text_justify_left, text_justify_left_middle, text_print_list, resolve_uw_display, text_set_printable_area
from texts import *

# choices_horizontal_menu, choices_single_option, choices_multiple_options
from choices import * 

PATH = os.path.dirname(__file__)+'/'

def set_var_lang(var):
	EN_FILE = 'misc/en_US.dat'
	BR_FILE = 'misc/pt_BR.dat'

	match INT_LANG:
		case 'en':
			with open(PATH+EN_FILE) as file:
				for line in file:
					line_row=line.split('=')
					if line_row[0] == var:
						TEXT = line_row[1].split(';')
						if len(TEXT) == 1:
							TEXT = str(TEXT[0].replace('\n',''))
						else:
							TEXT[len(TEXT)-1] = TEXT[len(TEXT)-1].replace('\n','')
		case 'br':
			with open(PATH+BR_FILE) as file:
				for line in file:
					line_row=line.split('=')
					if line_row[0] == var:
						TEXT = line_row[1].split(';')
						if len(TEXT) == 1:
							TEXT = str(TEXT[0].replace('\n',''))
						else:
							TEXT[len(TEXT)-1] = TEXT[len(TEXT)-1].replace('\n','')

	return TEXT

def set_language(lang):
	global YES_OR_NO , PROCEED_OR_ABORT, PROGRAM_TITLE, WELCOME_TEXT, DISK_OPTIONS3, DISK_OPTIONS4, SYSTEM_OPTIONS, DISK_SETUP_WELCOME

	YES_OR_NO = set_var_lang('YES_OR_NO')
	PROCEED_OR_ABORT = set_var_lang('PROCEED_OR_ABORT')
	PROGRAM_TITLE = set_var_lang('PROGRAM_TITLE')
	WELCOME_TEXT = set_var_lang('WELCOME_TEXT')
	DISK_OPTIONS3 = set_var_lang('DISK_OPTIONS3')
	DISK_OPTIONS4 = set_var_lang('DISK_OPTIONS4')
	SYSTEM_OPTIONS = set_var_lang('SYSTEM_OPTIONS')
	DISK_SETUP_WELCOME = set_var_lang('DISK_SETUP_WELCOME')
	
	pass

def initial_args(argv):
	global USERNAME, DISPLAY_USERNAME, HOSTNAME, TIME_ZONE, KEYBOARD_CONFIG, LANG, SYSTEM,  PASSWORD0, INT_LANG
	INT_LANG = 'en'
	HOSTNAME = 'arch'

	PASSWORD0 = '0'

	KNOW_SYSTEMS = ['sagittarius','phoenix','rubik','linuxtest']

	if len(sys.argv) > 1:
		for i, parameter in enumerate(sys.argv):
			match parameter.lower():
				case '-h':
					print(set_var_lang('HELP_ARG'))
					SYSTEM = 'generic'
					USERNAME = 'archlinux'
					DISPLAY_USERNAME = 'Arch Linux'
					HOSTNAME = 'arch'
					LANG = 'en_US.UTF-8'
					TIME_ZONE = 'Etc/GMT0'
					KEYBOARD_CONFIG = 'us-acentos'
					STEP = 10
				case '-s':
					if i+1 < len(sys.argv):
						HOSTNAME = sys.argv[i+1]
				case '-c':
					if i+1 < len(sys.argv):
						DISPLAY_NAME = sys.argv[i+1]
				case '-u':
					if i+1 < len(sys.argv):
						USERNAME = sys.argv[i+1]
				case '-p':
					if i+1 < len(sys.argv):
						PASSWORD0 = sys.argv[i+1]
				case '-i':
					if i+1 < len(sys.argv):
						if sys.argv[i+1] == 'en' or sys.argv[i+1]=='br':
							INT_LANG = sys.argv[i+1]

		SYSTEM = HOSTNAME
		
		if SYSTEM in KNOW_SYSTEMS:
			if SYSTEM == 'sagittarius':
				USERNAME = 'renata'
				DISPLAY_USERNAME = 'Renata Maria'
				HOSTNAME = SYSTEM
				LANG = '\'en_US.UTF-8\''
				TIME_ZONE = 'America/Fortaleza'
				KEYBOARD_CONFIG = 'br-abnt2'
			if SYSTEM == 'phoenix':
				USERNAME = 'renata'
				DISPLAY_USERNAME = 'Renata Maria'
				HOSTNAME = SYSTEM
				LANG = '\'en_US.UTF-8\''
				TIME_ZONE = 'America/Fortaleza'
				KEYBOARD_CONFIG = 'br-abnt2'
			if SYSTEM == 'rubik':
				USERNAME = 'renata'
				DISPLAY_USERNAME = 'Renata Maria'
				HOSTNAME = SYSTEM
				LANG = '\'en_US.UTF-8\''
				TIME_ZONE = 'America/Fortaleza'
				KEYBOARD_CONFIG = 'br-abnt2'
			if SYSTEM == 'linuxtest':
				USERNAME = 'renata'
				DISPLAY_USERNAME = 'Renata Maria'
				HOSTNAME = SYSTEM
				LANG = '\'en_US.UTF-8\''
				TIME_ZONE = 'America/Fortaleza'
				KEYBOARD_CONFIG = 'br-abnt2'
		else:
			SYSTEM = 'generic'
			USERNAME = 'archlinux'
			DISPLAY_USERNAME = 'Arch Linux'
			HOSTNAME = 'arch'
			LANG = 'en_US.UTF-8'
			TIME_ZONE = 'Etc/GMT0'
			KEYBOARD_CONFIG = 'us-acentos'
	else:
		SYSTEM = 'generic'
		USERNAME = 'archlinux'
		DISPLAY_USERNAME = 'Arch Linux'
		HOSTNAME = 'arch'
		LANG = 'en_US.UTF-8'
		TIME_ZONE = 'Etc/GMT0'
		KEYBOARD_CONFIG = 'br-abnt2'
		
	set_language(INT_LANG)
	
def permanent_title(term, program_title): # Defines a header with three lines

	position=list((0,0))
	program_title = text_justify_center(term, position, program_title)
	position[0]+=1
	navigation = text_justify_center(term, position, set_var_lang('NAVIGATION1'))
	print(term.clear())
	sys.stdout.write(term.move(0, 0))
	sys.stdout.write(term.bold(term.gray_on_blue(program_title)))
	sys.stdout.write(term.bold(term.blue_on_gray(navigation)))
	sys.stdout.write(term.csr(3, term.height))
	sys.stdout.write(term.move(3, 0))
	
	pass

def sysinfo(term, position):
	global VDA, SDA, NVME0N1, MEM, IMAGE_ID
	
	VDA = SDA = NVME0N1 = IMAGE_ID = False
	
	position2 = position3 = list((int(0),int(0)))
		
	position[0]+=1
	y = position[0]

	arch_id = subprocess.run(['sh','-c','cat /etc/os-release | grep -i image_id | awk -F\'=\' \'{print $2}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	image_id = arch_id.stdout.decode('utf-8').replace('\n','')
	if  image_id == 'archlinux':
		arch_version = subprocess.run(['sh','-c','cat /etc/os-release | grep -i image_version | awk -F\'=\' \'{print $2}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		print(text_justify_left(term, position, set_var_lang('IMAGE') + image_id))
		position[0]+=1
		print(text_justify_left(term, position, set_var_lang('IMAGE_VERSION') + arch_version.stdout.decode('utf-8').replace('\n','')))
		IMAGE_ID = True
	else:
		print(text_justify_left(term, position, set_var_lang('NOT_ARCH')))

	position = resolve_uw_display(term, 1)
	cpu = subprocess.run(['sh','-c','cat /proc/cpuinfo | grep -m 1 -i "model name" | awk -F: \'{print $2}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	print(text_justify_left(term, position,'CPU:'+cpu.stdout.decode('utf-8').replace('\n','')))
	position[0]+=1

	mem = subprocess.run(['sh','-c','cat /proc/meminfo | grep -i "memtotal" | awk \'{print $2}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	print(text_justify_left(term, position,'RAM: '+mem.stdout.decode('utf-8').replace('\n','')+' KiB'))
	MEM = mem.stdout.decode('utf-8').replace('\n','')+'K'
	position[0]+=2

	print(text_justify_left(term, position,set_var_lang('STORAGE_TOPOLOGY')))
	position = resolve_uw_display(term)
	lsblk = subprocess.run(['sh','-c','lsblk -a -o NAME,SIZE,TYPE,MODEL | grep disk | awk \'{print "Device: /dev/"$1" - Size: "$2" - Model: "$4" "$5" "$6" "$7}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	lsbblk_lines = lsblk.stdout.decode('utf-8').splitlines()
	for idx, lines in enumerate(lsbblk_lines):
		print(text_justify_left(term, position,lines))
		if lines.find('/dev/sda')!=-1:
			SDA = True
		if lines.find('/dev/nvme0n1')!=-1:
			NVME0N1 = True
		if lines.find('/dev/vda')!=-1:
			VDA = True
		position[0]+=1
	if NVME0N1 and SDA:
		SDA = False

	if not SDA and not NVME0N1 and not VDA:
		lsblk = subprocess.run(['sh','-c','fdisk -l | grep -i \'disk /dev\' | awk \'{print $1" "$2" "$3" "$4}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		lsbblk_lines = lsblk.stdout.decode('utf-8').splitlines()
		for idx, lines in enumerate(lsbblk_lines):
			print(text_justify_left(term, position,lines))
			if lines.find('/dev/sda')!=-1:
				SDA = True
			if lines.find('/dev/nvme0n1')!=-1:
				NVME0N1 = True
			if lines.find('/dev/vda')!=-1:
				VDA = True
			position[0]+=1
		if NVME0N1 and SDA:
			SDA = False

	position3 = resolve_uw_display(term)
	if position2[0] >= position3[0]:
		return position2
	else:
		return position3
		
def set_systemdisk(term, position):
	global SYSTEMDISK
	close_loop = False
	blk_devices_itens = ['0']

	lsblk = subprocess.run(['sh','-c','lsblk -a -o NAME,SIZE,TYPE,MODEL | grep disk | awk \'{print "Device: /dev/"$1" - Size: "$2" - Model: "$4" "$5" "$6" "$7}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	lsbblk_lines = lsblk.stdout.decode('utf-8').splitlines()	

	for i, item in enumerate(lsbblk_lines):
		if i==0:
			blk_devices_itens[0] = str(item)
		else:
			blk_devices_itens.append(str(item))

	position = resolve_uw_display(term)
	preserv_position = list((position[0],position[1]))

	while close_loop != True:
		position = preserv_position
		print(term.move_yx(position[0],position[1])+term.clear_eos())
		selected_item = choices_single_option(term, position, blk_devices_itens, 'Choose SYSTEM DISK')
		if selected_item != '0':
			SYSTEMDISK = selected_item.split()[1]
			position = resolve_uw_display(term)
			text = text_justify_left(term, position, set_var_lang('ACCEPT_SYSTEM_DISK')[0] +term.bold(SYSTEMDISK)+set_var_lang('ACCEPT_SYSTEM_DISK')[1])
			print(text)
			position[1] = position[1]+term.length(text)+2
			select_item=choices_horizontal_menu(term, position,YES_OR_NO)
			if select_item==YES_OR_NO[0]:
				close_loop = True
				return True
		else:
			position = resolve_uw_display(term)
			text = text_justify_left(term, position, set_var_lang('NO_SYSTEM_DISK'))
			print(text)
			position[1] = position[1]+(term.length(set_var_lang('NO_SYSTEM_DISK'))+2)
			select_item=choices_horizontal_menu(term, position,YES_OR_NO)
			if select_item==YES_OR_NO[0]:
				close_loop = True
				return False
			
def set_dualboot(term, position):
	global freespace_itens
	
	freespace = subprocess.run(['sh','-c','parted -s ' + SYSTEMDISK + ' print free | grep Free'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	freespace_lines = freespace.stdout.decode('utf-8').splitlines()
	
	freespace_itens = ['0']
	for i,line in enumerate(freespace_lines):
		if i==0:
			freespace_itens[0] = line.split()
		else:
			freespace_itens.append(line.split())
			
	i=0
	freespace_menu = ['0']
	while i < len(freespace_lines):
		if i == 0:
			freespace_menu[0]='Area ' + str(i+1) + ' size: ' + freespace_itens[i][2]
		else:
			freespace_menu.append('Area ' + str(i+1) + ' size: ' + freespace_itens[i][2])
		i+=1
	
	selected_area = choices_single_option(term, position, freespace_menu, 'Choose where to install Arch:')
	i = freespace_menu.index(selected_area)
	
	return i

def disk_setup(term, position):
	global NVME0N1, SDA, VDA, SYSTEMDISK, WIPEDISK, DUALBOOT, CUSTOMDISK
	
	SYSTEMDISK = ''
	FINISH = False
	WIPEDISK = DUALBOOT = CUSTOMDISK = False
	select_item = '0'
	select_items = list(('0'))
	DEFINED_SYSTEMDISK = False
	
	DISK_OPTIONS = set_var_lang('DISK_OPTIONS')
	
	text = text_justify_center(term, position, DISK_SETUP_WELCOME)
	print(term.bold(term.gray_on_blue(text)))

	position = resolve_uw_display(term,1)
	
	while FINISH != True:
		PRESERV_POSITION = position
		selected_item = choices_single_option(term, position, DISK_OPTIONS)
		if selected_item !='0':
			if selected_item == DISK_OPTIONS[0]:
				WIPEDISK = True
			if selected_item == DISK_OPTIONS[1]:
				DUALBOOT = True
			if selected_item == DISK_OPTIONS[2]:
				CUSTOMDISK = True
			FINISH = True
	
	print(term.move_yx(position[0],position[1])+term.clear_eos())
		
	select_item = '0'	
	if WIPEDISK or DUALBOOT:
		if NVME0N1 or SDA or VDA:
			if NVME0N1:	
				text = text_justify_left(term, position, set_var_lang('ACCEPT_SYSTEM_DISK')[0] +term.bold('/dev/nvme0n1')+set_var_lang('ACCEPT_SYSTEM_DISK')[1])
			if SDA:	
				text = text_justify_left(term, position, set_var_lang('ACCEPT_SYSTEM_DISK')[0]+term.bold('/dev/sda')+set_var_lang('ACCEPT_SYSTEM_DISK')[1])
			if VDA:	
				text = text_justify_left(term, position, set_var_lang('ACCEPT_SYSTEM_DISK')[0]+term.bold('/dev/vda')+set_var_lang('ACCEPT_SYSTEM_DISK')[1])
		else:
			text = text_justify_left(term, position, set_var_lang('NO_DEFAULT_DISK'))
		print(text)

		position[1] = position[1]+term.length(text)+2
		select_item=choices_horizontal_menu(term, position,YES_OR_NO)

		if select_item!='0':
			if select_item==YES_OR_NO[1]:
				position = resolve_uw_display(term)
				DEFINED_SYSTEMDISK = set_systemdisk(term, position)
			else:
				if NVME0N1:	
					SYSTEMDISK = '/dev/nvme0n1'
				if SDA:	
					SYSTEMDISK = '/dev/sda'
				if VDA:	
					SYSTEMDISK = '/dev/vda'
				DEFINED_SYSTEMDISK = True
	else:
		EFI = False
		ROOT = False

		mount_mnt = subprocess.run(['sh','-c','mount | grep /mnt'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		mount_mnt_lines = mount_mnt.stdout.decode('utf-8').splitlines()

		print(text_justify_left(term, position,'Pre-defined custom mount points:'))
		position[0] = position[0] + 2

		if len(mount_mnt_lines) >=1:
			for idx, lines in enumerate(mount_mnt_lines):
				print(text_justify_left(term, position, '-' + lines.replace('\n','') + str(position[0])))
				if (lines.find('vfat') != -1) and (lines.find('boot') != -1): EFI = True
				if (lines.find('ext4') != -1) and (lines.find('/mnt ') != -1): ROOT = True
				position[0] = position[0] + 1
			position[0] = position[0] + 1
			if EFI and ROOT: 
				DEFINED_SYSTEMDISK = True
			else:
				print(text_justify_left(term, position,'Need a EFI Vfat and a ROOT ext4 partitions to proceed!!'))
				key = term.inkey()
	if select_items =='0' or DEFINED_SYSTEMDISK == False:
		return False
	else:
		return True

def list_timezones():
	timez = subprocess.run(['sh','-c','timedatectl list-timezones'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	timez_lines = timez.stdout.decode('utf-8').splitlines()
	return timez_lines

def list_keymaps():
	keymaps = subprocess.run(['sh','-c','localectl list-keymaps'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	keymaps_lines = keymaps.stdout.decode('utf-8').splitlines()
	return keymaps_lines

def list_locales():
	locales = subprocess.run(['sh','-c','cat '+os.path.dirname(__file__)+'/misc/locale-list.dat'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	locales_lines = locales.stdout.decode('utf-8').splitlines()
	return locales_lines	

def set_usename(term,position):
	global USERNAME
	global DISPLAY_USERNAME

	USERNAME = input(term.move_yx(position[0],position[1]) + set_var_lang('ENTER_USERNAME') +term.clear_eos())
	USERNAME = USERNAME.lower()
	DISPLAY_USERNAME = input(term.move_yx(position[0]+1,position[1]) + set_var_lang('ENTER_DISPLAYNAME'))
	pass

def set_hostname(term,position):
	global HOSTNAME

	HOSTNAME = input(term.move_yx(position[0],position[1]) + set_var_lang('ENTER_HOSTNAME') + term.clear_eos())
	HOSTNAME = HOSTNAME.lower()
	pass
	
def set_locale(term,position):
	global LANG
	LOCAL_LANG = choices_single_option(term, position, list_locales(), set_var_lang('ENTER_LOCALE') + term.clear_eos())
	if LOCAL_LANG != '0':
		LANG = LOCAL_LANG
	pass

def set_timezone(term,position):
	global TIME_ZONE
	LOCAL_TIME_ZONE = choices_single_option(term, position, list_timezones(), set_var_lang('ENTER_TIMEZONE') + term.clear_eos())
	if LOCAL_TIME_ZONE != '0':
		TIME_ZONE = LOCAL_TIME_ZONE
	pass	

def set_password(term, position):
	global PASSWORD0

	PASSWORD1 = 1
	
	while PASSWORD0!=PASSWORD1:	
		print(term.move_yx(position[0],position[1]) + set_var_lang('DEFINING_PASSWORD')[0] + USERNAME + set_var_lang('DEFINING_PASSWORD')[1] + term.clear_eos())
		PASSWORD0=getpass.getpass(term.move_yx(position[0]+2,position[1]) + set_var_lang('ENTER_PASSWORD')[0] + USERNAME + set_var_lang('ENTER_PASSWORD')[1] +term.clear_eos())
		PASSWORD1=getpass.getpass(term.move_yx(position[0]+3,position[1]) + set_var_lang('CONFIRM_PASSWORD') +term.clear_eos())
		if PASSWORD0!=PASSWORD1:
			print(term.move_yx(position[0]+2,position[1]) + term.bold(set_var_lang('PASSWORDS_NOT_MATCH'))+term.clear_eos())
			with term.cbreak(), term.hidden_cursor():
				key = term.inkey()
		else:
			if PASSWORD0 == '':
				print(term.move_yx(position[0]+2,position[1]) + term.bold(set_var_lang('EMPTY_PASSWORDS'))+term.clear_eos())
				PASSWORD1 = '1'
				with term.cbreak(), term.hidden_cursor():
					key = term.inkey()
	pass

def set_keyboard(term,position):
	global KEYBOARD_CONFIG
	LOCAL_KEYBOARD_CONFIG = choices_single_option(term, position, list_keymaps(), set_var_lang('KEYMAP') + term.clear_eos())
	if LOCAL_KEYBOARD_CONFIG != '0':
		KEYBOARD_CONFIG = LOCAL_KEYBOARD_CONFIG
	pass	

def user_info(term, position):
	finish = True
	global LANG, USERNAME, DISPLAY_USERNAME, HOSTNAME, TIME_ZONE, KEYBOARD_CONFIG

	USER_INFO_OPTIONS = set_var_lang('USER_INFO_OPTIONS')
	USER_INFO_TEXT = set_var_lang('USER_INFO_TEXT')

	selected_items = list(('0'))
	
	position = resolve_uw_display(term,1)
	preserv_position = position
	while finish:
		USER_INFO=[term.bold(SYSTEM) + USER_INFO_TEXT[0],
				   USER_INFO_TEXT[1],
				   USER_INFO_TEXT[2] + USERNAME,
				   USER_INFO_TEXT[3] + DISPLAY_USERNAME,
				   USER_INFO_TEXT[4] + HOSTNAME,
				   USER_INFO_TEXT[5] + LANG,
				   USER_INFO_TEXT[6] + TIME_ZONE,
				   USER_INFO_TEXT[7] + KEYBOARD_CONFIG]
		
		position = preserv_position
		text_print_list(term, position, USER_INFO)
		position = resolve_uw_display(term,1)
		selected_item = choices_horizontal_menu(term, position, YES_OR_NO, set_var_lang('ACCEPT_THIS'))
		if selected_item == YES_OR_NO[1]:
			position = resolve_uw_display(term,1)
			selected_items=choices_multiple_options(term, position, USER_INFO_OPTIONS, set_var_lang('MULTIPLE_SELECTIONS'))
			if selected_items[0] != '0':
				print(term.move_yx(position[0],position[1])+term.clear_eos())
				for idx, item_line in enumerate(selected_items):
					if item_line==USER_INFO_OPTIONS[0]:
						set_usename(term, position)
					if item_line==USER_INFO_OPTIONS[1]:
						set_hostname(term, position)
					if item_line==USER_INFO_OPTIONS[2]:
						set_locale(term, position)
					if item_line==USER_INFO_OPTIONS[3]:
						set_timezone(term, position)
					if item_line==USER_INFO_OPTIONS[4]:
						set_keyboard(term, position)
				position = preserv_position
			else:
				finish = True
				return False
		else:
			if selected_item == YES_OR_NO[0]:
				position = resolve_uw_display(term,1)
				if PASSWORD0 == '0':
					set_password(term, position)
				finish = True
				return True
			else:
				finish = True
				return False

def set_msfonts():
	MSFONTS_PATH = '/mnt/usr/share/fonts/WindowsFonts'
	MSFONTS_FILE = PATH + 'assets/msfonts.7z.001'
	
	try:
		os.makedirs(MSFONTS_PATH)
		
	except FileExistsError:
		print(f"One or more directories in '{MSFONTS_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{MSFONTS_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")
	result1 = subprocess.run(['sh', '-c','7z e ' + MSFONTS_FILE + ' -o' + MSFONTS_PATH + '/'])
	result2 = subprocess.run(['sh', '-c','arch-chroot /mnt fish -c \'chmod 644 ' + MSFONTS_PATH + '/*\''])
	result3 = subprocess.run(['sh', '-c','arch-chroot /mnt fc-cache –force'])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result1)+'\n'+str(result2)+'\n'+str(result3)+'\n')
	pass 

def set_telaicons():
	TELAICONS_PATH = '/mnt/home/' + USERNAME + '/.local/share/icons'
	TELAICONS_FILE = PATH + 'assets/telaicons.7z'

	try:
		os.makedirs(TELAICONS_PATH)
		print(f"Nested directories '{TELAICONS_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{TELAICONS_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{TELAICONS_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")
	result=subprocess.run(['sh', '-c','7z x ' + TELAICONS_FILE + ' -o' + TELAICONS_PATH + '/'])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result)+'\n')
	pass 

def set_alacritty():
	ALACRITTY_PATH = '/mnt/home/' + USERNAME + '/.config/alacritty'
	ALACRITTY_FILE = PATH + 'assets/alacritty.toml'
	
	if EXTRAS == True:
		try:
			os.makedirs(ALACRITTY_PATH)
			print(f"Nested directories '{ALACRITTY_PATH}' created successfully.")
		except FileExistsError:
			print(f"One or more directories in '{ALACRITTY_PATH}' already exist.")
		except PermissionError:
			print(f"Permission denied: Unable to create '{ALACRITTY_PATH}'.")
		except Exception as e:
			print(f"An error occurred: {e}")
		result=subprocess.run(['sh', '-c','cp -v ' + ALACRITTY_FILE + ' ' + ALACRITTY_PATH + '/'])
		with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
			logfile.write(str(result)+'\n')
	pass
	
def set_fish_functions():
	FISH_FUNCTIONS_PATH = '/mnt/home/' + USERNAME + '/.config/fish/functions'
	FISH_FUNCTIONS_FILES = 'assets/functions/*'
	
	try:
		os.makedirs(FISH_FUNCTIONS_PATH)
		print(f"Nested directories '{FISH_FUNCTIONS_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{FISH_FUNCTIONS_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{FISH_FUNCTIONS_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")
	result = subprocess.run(['sh', '-c','cp -v ' + PATH + FISH_FUNCTIONS_FILES + ' ' + FISH_FUNCTIONS_PATH + '/'])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result)+'\n')
	pass 

def set_plymouth():
	PLYTMOUTH_THEME_PATH = '/mnt/usr/share/plymouth/themes/PoweredByArchV2'
	PLYTMOUTH_THEME_FILES = 'assets/PoweredByArchV2/*'
	PLYTMOUTH_CONF = 'assets/plymouthd.conf'
	PLYTMOUTH_CONF_PATH = '/mnt/etc/plymouth'
	
	try:
		os.makedirs(PLYTMOUTH_THEME_PATH)
		print(f"Nested directories '{PLYTMOUTH_THEME_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{PLYTMOUTH_THEME_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{PLYTMOUTH_THEME_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")

	try:
		os.makedirs(PLYTMOUTH_CONF_PATH)
		print(f"Nested directories '{PLYTMOUTH_CONF_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{PLYTMOUTH_CONF_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{PLYTMOUTH_CONF_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")

	result1=subprocess.run(['sh', '-c','cp -Rv ' + PATH + PLYTMOUTH_THEME_FILES + ' ' + PLYTMOUTH_THEME_PATH + '/'])
	result2=subprocess.run(['sh', '-c','cp -v ' + PATH + PLYTMOUTH_CONF + ' ' + PLYTMOUTH_CONF_PATH + '/'])
	result3=subprocess.run(['sh', '-c','arch-chroot /mnt sh /home/' + USERNAME + '/ArchInstall/scripts/setinitram.sh'])
	result4=subprocess.run(['sh', '-c','arch-chroot /mnt mkinitcpio -P'])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result1)+'\n'+str(result2)+'\n'+str(result3)+'\n'+str(result4)+'\n')
	pass 

def set_sddm_theme():
	SDDM_DEFAULT_CONF = ['[Theme]','\nCurrent=breeze\n']
	SDDM_D_PATH = '/mnt/etc/sddm.conf.d'
	SDDM_DEFAULT_CONF_FILE = '/default.conf'
	
	try:
		os.makedirs(SDDM_D_PATH)
		print(f"Nested directories '{SDDM_D_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{SDDM_D_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{SDDM_D_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")

	with open(SDDM_D_PATH + SDDM_DEFAULT_CONF_FILE, 'a') as FILE:
		for i, line in enumerate(SDDM_DEFAULT_CONF):
				FILE.writelines(line)
	pass 		

def populate_options():
	PACKAGES_FILE_PATH = PATH + 'misc/first-packages.dat'
	SYSTEM_OPTIONS=['0']
	DEFAULT_OPTIONS=['0']
	
	with open(PACKAGES_FILE_PATH) as file:
		for ITEM_RAW in file:
			ITEM_RAW=ITEM_RAW.replace('\n','')
			ITEM_LINE = ITEM_RAW.split(';')
			if SYSTEM_OPTIONS[0]=='0':
				SYSTEM_OPTIONS[0]=ITEM_LINE[1]
			else:
				SYSTEM_OPTIONS.append(ITEM_LINE[1])
			if ITEM_LINE[0]=='#':
				if DEFAULT_OPTIONS[0]=='0':
					DEFAULT_OPTIONS[0]=ITEM_LINE[1]
				else:
					DEFAULT_OPTIONS.append(ITEM_LINE[1])
	return SYSTEM_OPTIONS, DEFAULT_OPTIONS
	
def read_options(selected_items):
	PACKAGES_FILE_PATH = PATH + 'misc/first-packages.dat'
	PACKAGES = ['0']

	with open(PACKAGES_FILE_PATH) as file:
		for ITEM_RAW in file:
			ITEM_RAW = ITEM_RAW.replace('\n','')
			ITEM_RAW = ITEM_RAW.split(';')
			if ITEM_RAW[1] in selected_items:
				if PACKAGES[0] == '0':
					PACKAGES = ITEM_RAW[2].split(' ')
				else:
					PACKAGES = PACKAGES + ITEM_RAW[2].split(' ')
					
	return PACKAGES

def system_options(term, position):
	SYSTEM_OPTIONS, DEFAULT_OPTIONS = populate_options()
	finish = False
	preserv_position = position
	MESA = 'Mesa combo - For systems with GPUs/iGPUS AMD or Intel'
	NVIDIA = 'NVidia combo - For systems with GPUs NVidia'
	GNOME = 'GNOME Basic - Minimal options - file manager, terminal, tweaks...'
	KDE = 'Plasma/KDE Basic -  Minimal options - file manager, terminal...'
	MESA_NVIDIA_GNOME_KDE = 'Mesa/NVidia or Gnome/Plasma are mutual excludents. Press any key...'
	selected_items = list(('0'))
	
	choices_set_options_limit(term, 30)
	
	SYSTEM_OPTIONS.remove('BASE')
	
	while finish == False:
		selected_items=choices_multiple_options(term, position, SYSTEM_OPTIONS, 'CHOOSE_COMPONENTS', DEFAULT_OPTIONS)
		if selected_items[0] != '0':
			if ((MESA in selected_items) and (NVIDIA in selected_items)) or ((GNOME in selected_items) and (KDE in selected_items)):
				print(term.move_yx(position[0]+len(SYSTEM_OPTIONS)+3, position[1]) + MESA_NVIDIA_GNOME_KDE)
				with term.cbreak(), term.hidden_cursor():
					key = term.inkey()	
			else:
				finish = True
		position = preserv_position
	return selected_items

def disk_definition(term):
	create_gpt_label = create_efi_partition = create_root_partition = format_efi = format_root = '0'
	mkswapfile = swapon = '0'
	
	DISK_DEFINITION = set_var_lang('DISK_DEFINITION')

	disk_commands = list((term.bold(DISK_DEFINITION[0]),' '))
	
	if WIPEDISK:
		if SYSTEMDISK.find('nvme') == -1:
			efi_number = '1'
			root_number = '2'
		else:						
			efi_number = 'p1'
			root_number = 'p2'
		create_gpt_label      = DISK_DEFINITION[1] + term.bold(SYSTEMDISK) + DISK_DEFINITION[2]
		create_efi_partition  = DISK_DEFINITION[3] + term.bold(SYSTEMDISK) + DISK_DEFINITION[4]
		create_root_partition = DISK_DEFINITION[5] + term.bold(SYSTEMDISK) + DISK_DEFINITION[6]
		format_efi            = DISK_DEFINITION[7] + term.bold(SYSTEMDISK + efi_number) + DISK_DEFINITION[8] + term.bold('/boot/efi')
		format_root           = DISK_DEFINITION[7] + term.bold(SYSTEMDISK + root_number) + DISK_DEFINITION[9] + term.bold('/')
	
	if DUALBOOT:
		position = resolve_uw_display(term, 1)
		i = set_dualboot(term, position)
		create_root_partition = DISK_DEFINITION[5] + freespace_itens[i][2] + DISK_DEFINITION[13]

	mkswapfile = DISK_DEFINITION[12] + MEM

	for verify_disk_options in [create_gpt_label, create_efi_partition, create_root_partition, format_efi, format_root, mkswapfile, swapon]:
		if verify_disk_options != '0':
			disk_commands.append(verify_disk_options)

	return disk_commands

def packages_definition(term, selected_items):
	SELECTED_PACKAGES = list((term.bold(set_var_lang('PACKAGES_INSTALLED')),' '))

	for i in range(0,len(selected_items)):
		SELECTED_PACKAGES.append(' - ' + selected_items[i] + '\n')
		
	return SELECTED_PACKAGES

def confirm_options(term, position, selected_items):
	
	x = time.localtime()
	prefix = str(x.tm_year)+'.'+str(x.tm_mon)+'.'+str(x.tm_mday)+'.'+str(x.tm_hour)+str(x.tm_min)
	
	USER_INFO_TEXT = set_var_lang('USER_INFO_TEXT2')
	
	global LOG_FILE_NAME, COMPLETE_LOG_FILE_NAME
	LOG_FILE_NAME = prefix + '_first.log'
	LOG_FILE_PATH = PATH + 'logs/'
	COMPLETE_LOG_FILE_NAME = LOG_FILE_PATH + LOG_FILE_NAME 	
	
	USER_INFO=[term.bold(USER_INFO_TEXT[0]),
			   USER_INFO_TEXT[1],
			   USER_INFO_TEXT[2] + term.bold(USERNAME),
		       USER_INFO_TEXT[3] + term.bold(DISPLAY_USERNAME),
		       USER_INFO_TEXT[4] + term.bold(HOSTNAME),
		       USER_INFO_TEXT[5] + term.bold(LANG),
		       USER_INFO_TEXT[6] + term.bold(TIME_ZONE),
		       USER_INFO_TEXT[7] + term.bold(KEYBOARD_CONFIG)]
	
	DISK_COMMANDS = disk_definition(term)
	SELECTED_PACKAGES = packages_definition(term, selected_items)
	
	position = resolve_uw_display(term,1)
	text_print_list(term, position, USER_INFO)

	position = resolve_uw_display(term,1)
	text_print_list(term, position, DISK_COMMANDS)

	position = resolve_uw_display(term,1)
	text_print_list(term, position, SELECTED_PACKAGES)

	try:
		os.makedirs(LOG_FILE_PATH)
	except FileExistsError:
		print("")
	except PermissionError:
		print("")
	except Exception as e:
		print("")

	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		for i,WRITE_LOG_LINE in enumerate(USER_INFO):
			logfile.write(WRITE_LOG_LINE+'\n')
		for i,WRITE_LOG_LINE in enumerate(DISK_COMMANDS):
			logfile.write(WRITE_LOG_LINE+'\n')
		for i,WRITE_LOG_LINE in enumerate(SELECTED_PACKAGES):
			logfile.write(WRITE_LOG_LINE+'\n')
	return True

def popen_progress(term, position, text, cmd, TIMER_LIMIT = 480):
	index = 0 
	TIMER = 0
	result = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	while True:
		if TIMER >= (TIMER_LIMIT / 2):
			result.terminate()
		if (result.poll() is not None):
			break
		index = show_progress(term, position, text, index)
		time.sleep(2)
		TIMER +=1

	text=text_justify_left(term, position, text)
	print(text + term.clear_eol())

	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write('\nCommand: ' + str(cmd) + '\nCommand return:' + str(result.poll()) + '\n' + str(result)+'\n')

def prepare_disk(term):
	create_gpt_label = create_efi_partition = create_root_partition = format_efi = format_boot = format_root = '0'
	mount_root = mount_efi = mkdir_efi = mkswapfile = swapon = '0'

	term.move_yx(4,0)
	term.clear_eos()

	mkswapfile = 'mkswap -U clear --size ' + MEM + ' --file /mnt/swapfile'
	swapon     = 'swapon /mnt/swapfile'

	if WIPEDISK:
		if SYSTEMDISK.find('nvme') == -1:
			efi_number = '1'
			root_number = '2'
		else:						
			efi_number = 'p1'
			root_number = 'p2'
		create_gpt_label      = 'parted -s --align optimal ' + SYSTEMDISK + ' mklabel gpt'
		create_efi_partition  = 'parted -s --align optimal ' + SYSTEMDISK + ' mkpart PRIMARY fat32 0% 512M'
		create_root_partition = 'parted -s --align optimal ' + SYSTEMDISK + ' mkpart PRIMARY ext4 512M 100%'
		format_efi            = 'mkfs.fat -F32 -n EFI ' + SYSTEMDISK + efi_number
		format_root           = 'mkfs.ext4 -F -L Root ' + SYSTEMDISK + root_number
		mount_root            = 'mount ' + SYSTEMDISK + root_number + ' /mnt'
		mkdir_efi             = 'mkdir -p /mnt/boot/efi'
		mount_efi             = 'mount ' + SYSTEMDISK + efi_number + ' /mnt/boot/efi'

		for i, command_to_run in enumerate([create_gpt_label, create_efi_partition, create_root_partition, format_efi, format_root, mount_root, mkdir_efi, mount_efi, mkswapfile, swapon]):
			if command_to_run != '0':
				match i:
					case 0:
						text = 'Creating GPT label'
					case 1:
						text = 'Creating EFI partition'
					case 2:
						text = 'Creating root partition'
					case 3:
						text = 'Formating EFI'
					case 4:
						text = 'Formating root partition'
					case 4:
						text = 'Mounting root partition'
					case 5:
						text = 'Creating EFI dir'
					case 6:
						text = 'Mounting EFI partition'
					case 7:
						text = 'Creating swapfile'
					case 8:
						text = 'Enabling swapfile'
				cmd = ['sh','-c',command_to_run]
				position = resolve_uw_display(term) 	
				popen_progress(term, position, text, cmd)
				
	if DUALBOOT:
		position = resolve_uw_display(term)
		i = set_dualboot(term, position)	
		
		create_root_partition = 'parted -s --align optimal ' + SYSTEMDISK + ' mkpart ROOT ext4 ' + freespace_itens[i][0] + ' ' + freespace_itens[i][1]
		cmd = ['sh','-c',create_root_partition]
		result = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		popen_progress(term, position, 'Configuring disks', cmd)
					
		device_id_command = subprocess.run(['sh','-c','blkid | grep ' + SYSTEMDISK + ' | grep ROOT | awk -F\':\' \'{print $1}\''], stdout=subprocess.PIPE, stderr=subprocess.PIPE)	
		device_id = device_id_command.stdout.decode('utf-8').splitlines()
		device_id = device_id[0]
		format_root = 'mkfs.ext4 -F -L Root ' + str(device_id)
		mount_root  = 'mount ' + str(device_id) + ' /mnt'
		
		EFI_id_command = subprocess.run(['sh','-c','fdisk -l ' + SYSTEMDISK + ' | grep EFI' ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)	
		EFI_id = EFI_id_command.stdout.decode('utf-8').splitlines()
		EFI_id = EFI_id[0].split()
		EFI_id = EFI_id[0]
		
		mkdir_efi = 'mkdir -p /mnt/boot/efi'
		mount_efi = 'mount ' + str(EFI_id) + ' /mnt/boot/efi'
		
		for i, command_to_run in enumerate([format_root, mount_root, mkdir_efi, mount_efi, mkswapfile, swapon]):
			if command_to_run != '0':
				match i:
					case 0:
						text = 'Formating root'
					case 1:
						text = 'Mounting root'
					case 2:
						text = 'Creating EFI dir'
					case 3:
						text = 'Mounting EFI'
					case 4:
						text = 'Creating swapfile'
					case 4:
						text = 'Enabling swapfile'
				position = resolve_uw_display(term)
				cmd = ['sh','-c',command_to_run]
				popen_progress(term, position, text, cmd)
 
	x = time.localtime()
	sufix = str(x.tm_year)+'.'+str(x.tm_mon)+'.'+str(x.tm_mday)+'.'+str(x.tm_hour)+str(x.tm_min)

	if os.path.isdir('/mnt/home/'+USERNAME): # Checks the existence of user home folder and rename it
		result = subprocess.run(['sh','-c','mv -v /mnt/home/' + USERNAME + ' /mnt/home/'+USERNAME+'.'+sufix], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
			logfile.write(str(result)+'\n')

	return True

def read_files(file_name):
	try:
		file = open(PATH+file_name)
		packages = ''
		for package in file:
			if packages == '':
				packages = package.replace('\n','')
			else:
				packages = packages + ' ' + package.replace('\n','')
		file.close()
		return packages
	except Exception:
		packages = '0'
		return packages

def run_reflector():
	cmd = 'reflector --latest 10 --sort rate --save /etc/pacman.d/mirrorlist'
	REFLECTOR_TEXT = set_var_lang('REFLECTOR')
	print(REFLECTOR_TEXT.replace('#','\n'))
	result = subprocess.run(['sh','-c', cmd])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write('\nCommand: ' + str(cmd) + '\nCommand return:' + str(result.returncode) + '\n' + str(result)+'\n')
	pass 

def prepare_chroot():
	file_name = 'misc/pacstrap.dat'
	PACSTRAP = list(('0'))
	
	packages = read_files(file_name)
	if packages != '0':
		# run_reflector() # Update mirrors
		PACSTRAP[0] = 'pacstrap /mnt '+ packages
		PACSTRAP.append('genfstab -U -p /mnt >> /mnt/etc/fstab')
		return PACSTRAP

def set_pacman(): # Execute before arch-chroot - Enable multilib, parallel downloads and fancy apearence on pacman 
	cmd = ['sh', '-c','sh ' + PATH + 'scripts/pacman-conf.sh']
	result = subprocess.run(cmd,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write('\nCommand: ' + str(cmd) + '\nCommand return:' + str(result.returncode) + '\n' + str(result)+'\n')
	pass
	
def chroot_packages(term, selected_items):
			
	cmd = ['sh','-c','cp -v /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist']
	result = subprocess.run(cmd,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write('\nCommand: ' + str(cmd) + '\nCommand return:' + str(result.returncode) + '\n' + str(result)+'\n')

	cmd_base = ['arch-chroot', '/mnt', 'pacman', '-Sy', '--noconfirm', '--needed']
			
	selected_items.append('BASE')
	
	PACKAGES = read_options(selected_items)
	REMAINDER = len(PACKAGES) % 8
	LOOP = (len(PACKAGES) - REMAINDER) / 8
	i = 1
	ITEM = 0
	position = resolve_uw_display(term,1)

	while i <= LOOP:
		PACK=['0']
		for y in range (0,8):
			if y == 0:
				PACK[0] = PACKAGES[y+ITEM]
			else:
				PACK.append(PACKAGES[y+ITEM])
		cmd = cmd_base + PACK
		popen_progress(term, position, 'Instaling packages ' + str(i), cmd, 900)
		ITEM = y + (ITEM + 1)
		i+=1
		time.sleep(20)
		
	cmd = cmd_base
	for x in range (ITEM, ITEM + REMAINDER):
		cmd.append(PACKAGES[x])
	popen_progress(term, position, 'Instaling packages ' + str(LOOP + 1), cmd)
	
	pass 

def set_regional_settings():
	result1=subprocess.run(['sh', '-c','arch-chroot /mnt ln -sf /usr/share/zoneinfo/' + TIME_ZONE + ' /etc/localtime'])
	result2=subprocess.run(['sh', '-c','arch-chroot /mnt timedatectl set-ntp 1'])
	result3=subprocess.run(['sh', '-c','arch-chroot /mnt timedatectl set-timezone ' + TIME_ZONE])
	result4=subprocess.run(['sh', '-c','arch-chroot /mnt sed -i s/#pt_BR.UTF-8/pt_BR.UTF-8/g /etc/locale.gen'])
	result5=subprocess.run(['sh', '-c','arch-chroot /mnt sed -i s/#' + LANG + '/' + LANG + '/g /etc/locale.gen'])
	result6=subprocess.run(['sh', '-c','arch-chroot /mnt locale-gen'])
	result7=subprocess.run(['sh', '-c','echo LANG=' + LANG + ' >> /mnt/etc/locale.conf'])
	result8=subprocess.run(['sh', '-c','localectl set-keymap ' + KEYBOARD_CONFIG])
	result9=subprocess.run(['sh', '-c','cp -v /etc/vconsole.conf /mnt/etc/vconsole.conf'])
	
	resultA=0	
	if KEYBOARD_CONFIG == 'us-acentos':
		resultA=subprocess.run(['sh', '-c','echo "GTK_IM_MODULE=cedilla\nQT_IM_MODULE=cedilla" >> /mnt/etc/environment'])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result1)+'\n' + str(result2)+'\n'+ str(result3)+'\n'+ str(result4)+'\n'+ str(result5)+'\n'+ str(result6)+'\n'+ str(result7)+'\n'+ str(result8)+'\n'+ str(result9)+'\n'+ str(resultA)+'\n')
	pass 

def set_hosts_files(): # Set hostname and config hosts file
	SAMPLE_HOSTS = 'assets/hosts.txt'
	HOSTS_FILE   = '/mnt/etc/hosts'

	try:
		subprocess.run(['sh', '-c','echo ' + HOSTNAME + ' > /mnt/etc/hostname'])
		
		sample_hosts = open(PATH+SAMPLE_HOSTS)
		hosts_file = open(HOSTS_FILE, 'r+')
		for idx, line in enumerate(sample_hosts.readlines()):
			if line.find('#HOSTNAME') != -1:
				hosts_file.write(line.replace('#HOSTNAME',HOSTNAME))
			else:
				hosts_file.write(line)
		sample_hosts.close()
		hosts_file.close()
		return True		
	except Exception:
		return False	
     
def set_pass(): # Create main user and set root password
	result1=subprocess.run(['sh', '-c','arch-chroot /mnt useradd -m -g users -G wheel -c \'' + DISPLAY_USERNAME + '\' -s /usr/bin/fish -d /home/' + USERNAME + ' '+ USERNAME])
	result2=subprocess.run(['sh', '-c','mkdir /mnt/home/' + USERNAME + '/ArchInstall'])
	result3=subprocess.run(['sh', '-c','cp -Rv ' + os.path.dirname(__file__) + '/* /mnt/home/' + USERNAME + '/ArchInstall/'])
	result4=subprocess.run(['sh', '-c','arch-chroot /mnt sh /home/' + USERNAME + '/ArchInstall/scripts/setpass.sh \''+PASSWORD0+'\' '+USERNAME])
	result4_without_password = str(result4).replace(PASSWORD0,'')
	print('Press any key')
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result1)+'\n' + str(result2)+'\n'+ str(result3)+'\n'+ result4_without_password+'\n')
	pass
	
def set_bootloader():
	result=subprocess.run(['sh', '-c','arch-chroot /mnt sh /home/' + USERNAME + '/ArchInstall/scripts/mkgrub.sh'])
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result)+'\n')

	pass

def set_daemons():
	STRING1 = '#AddressFamily any'
	STRING2 = 'AddressFamily inet'
	result1=subprocess.run(['sh', '-c','sed -i \'s/' + STRING1 + '/' + STRING2 + '/g\' /mnt/etc/ssh/sshd_config'])
	result2=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable NetworkManager'])
	result3=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable sshd'])
	result4=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable bluetooth'])
	result5=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable cronie'])
	result6=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable ModemManager'])
	result7=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable tuned'])
	result8=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable tuned-ppd'])
	
	if GNOME_BASIC == True:
		result9=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable gdm'])
	if PLASMA_BASIC == True:
		result9=subprocess.run(['sh', '-c','arch-chroot /mnt systemctl enable sddm'])
		set_sddm_theme()
	with open(COMPLETE_LOG_FILE_NAME,'a+') as logfile:
		logfile.write(str(result1)+'\n' + str(result2)+'\n'+ str(result3)+'\n'+ str(result4)+'\n'+ str(result5)+'\n'+ str(result6)+'\n'+ str(result7)+'\n'+ str(result8)+'\n'+ str(result9)+'\n')
	pass 

def set_second_autostart():
	AUTOSTART_PATH = '/mnt/home/' + USERNAME + '/.config/autostart'
	AUTOSTART_FILE = AUTOSTART_PATH + '/second.desktop'
	SECOND_DESKTOP1 = ['[Desktop Entry]\n',
					  'Exec=alacritty -o "window.dimensions.lines=40" -o "window.dimensions.columns=100" -e /home/' + USERNAME + '/ArchInstall/second -i ' + INT_LANG + ' && exit\n',
					  'Icon=application-x-shellscript\n',
					  'Name=Autostart Wizard\n',
					  'Terminal=false\n',
					  'Type=Application\n',
					  'X-KDE-AutostartScript=true\n' ]
	SECOND_DESKTOP2 = ['[Desktop Entry]\n',
				  'Exec=alacritty -o "window.dimensions.lines=40" -o "window.dimensions.columns=100" -e /home/' + USERNAME + '/ArchInstall/second -i ' + INT_LANG + ' -n && exit\n',
				  'Icon=application-x-shellscript\n',
				  'Name=Autostart Wizard\n',
				  'Terminal=false\n',
				  'Type=Application\n',
				  'X-KDE-AutostartScript=true\n' ]

	try:
		os.makedirs(AUTOSTART_PATH)
		print(f"Nested directories '{AUTOSTART_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{AUTOSTART_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{AUTOSTART_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")
	with open(AUTOSTART_FILE, 'a') as FILE:
		if NO_GNOME_CUSTOMIZATIONS == True:
			for i, line in enumerate(SECOND_DESKTOP2):
				FILE.writelines(line)
		else:
			for i, line in enumerate(SECOND_DESKTOP1):
				FILE.writelines(line)
	pass 
 
def save_log_file():
	FINAL_LOG_FILE_PATH = '/mnt/home/' + USERNAME + '/ArchInstall/logs'
	
	try:
		os.makedirs(FINAL_LOG_FILE_PATH)
		print(f"Nested directories '{FINAL_LOG_FILE_PATH}' created successfully.")
	except FileExistsError:
		print(f"One or more directories in '{FINAL_LOG_FILE_PATH}' already exist.")
	except PermissionError:
		print(f"Permission denied: Unable to create '{FINAL_LOG_FILE_PATH}'.")
	except Exception as e:
		print(f"An error occurred: {e}")
		
	subprocess.run(['sh','-c','cp -v ' + COMPLETE_LOG_FILE_NAME + ' ' + FINAL_LOG_FILE_PATH])
	
def set_owner():
	subprocess.run(['sh', '-c','arch-chroot /mnt /usr/bin/fish -c \'chown -Rv ' + USERNAME + ':users /home/' + USERNAME + '/{\'\',\'.\'}*\''])
   
def main():
	global STEP
	STEP = 1
	position = list((0,0))

	term = blessed.Terminal()
	
	initial_args(sys.argv)
	set_int_lang(term, INT_LANG)
		 
	with term.fullscreen():
		try:
			while True:
				match STEP:
					case 1: # Print inital statements and disk setup step
						permanent_title(term, PROGRAM_TITLE) # Set the header with PROGRAM_TITLE text
						position = resolve_uw_display(term, -1)
						preserv_position = position
						text_print_list(term, position, WELCOME_TEXT)
						position = resolve_uw_display(term)
						select_item=choices_horizontal_menu(term, position,PROCEED_OR_ABORT)
						if select_item==PROCEED_OR_ABORT[1]:
							break
						position = preserv_position
						print(term.move_yx(position[0], position[1]) + term.clear_eos())
						step_title = text_justify_center(term, position, set_var_lang('SYSTEM_INFO'))
						print(term.bold(term.gray_on_blue(step_title)))
						position = resolve_uw_display(term)
						position = sysinfo(term, position)
						position[0]+=1
						if disk_setup(term, position):
							STEP+=1
					case 2:
						permanent_title(term, PROGRAM_TITLE) # usa a função que segura o cabeçalho do terminal
						position = resolve_uw_display(term,-1)
						step_title = text_justify_center(term, position, set_var_lang('MOMENT1_1'))
						print(term.bold(term.gray_on_blue(step_title)))
						if user_info(term, position):
							STEP+=1
						else:
							STEP-=1
					case 3:
						permanent_title(term, PROGRAM_TITLE) # usa a função que segura o cabeçalho do terminal
						position = resolve_uw_display(term,-1)
						step_title = text_justify_center(term, position, set_var_lang('MOMENT1_2'))
						print(term.bold(term.gray_on_blue(step_title)))
						selected_items = system_options(term, position)
						if selected_items[0]!='0':
							STEP+=1
						else:
							STEP-=1
					case 4:
						permanent_title(term, PROGRAM_TITLE) # usa a função que segura o cabeçalho do terminal
						position = resolve_uw_display(term,-1)
						permanent_position=position
						step_title = text_justify_center(term, position, set_var_lang('MOMENT1_3'))
						print(term.bold(term.gray_on_blue(step_title)))
						if confirm_options(term, position, selected_items):
							STEP+=1
						else:
							STEP-=1
					case 5:
						position = resolve_uw_display(term,1)
						CASE_5 = set_var_lang('CASE_5')
						proceed_or_abort = choices_horizontal_menu(term, position, PROCEED_OR_ABORT, term.blink(term.bold(CASE_5[0])) + term.clear_eos())
						if proceed_or_abort == PROCEED_OR_ABORT[0]:
							step_title = text_justify_center(term, permanent_position, CASE_5[1])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							prepare_disk(term)
							step_title = text_justify_center(term, permanent_position, CASE_5[2])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							PACSTRAP = prepare_chroot()
							for idx, command_to_run in enumerate(PACSTRAP):
								if idx == 0:
									cmd = ['sh','-c',command_to_run]
									position = resolve_uw_display(term,1)
									popen_progress(term, position, 'Executing pacstrap',cmd, 600)
								else:
									cmd = ['sh','-c',command_to_run]
									position = resolve_uw_display(term)
									popen_progress(term, position, 'Executing genfstab',cmd)

							step_title = text_justify_center(term, permanent_position, CASE_5[3])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							set_pacman()
							step_title = text_justify_center(term, permanent_position, CASE_5[4])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							chroot_packages(term, selected_items)
							step_title = text_justify_center(term, permanent_position, CASE_5[5])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							set_hosts_files()
							step_title = text_justify_center(term, permanent_position, CASE_5[6])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							set_regional_settings()
							step_title = text_justify_center(term, permanent_position, CASE_5[7])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							set_pass()
							step_title = text_justify_center(term, permanent_position, CASE_5[8])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							set_bootloader()
							step_title = text_justify_center(term, permanent_position, CASE_5[9])
							print(term.bold(term.gray_on_blue(step_title))+term.clear_eos())
							set_daemons()
							set_alacritty()
							set_msfonts()
							set_telaicons()
							set_plymouth()
							set_second_autostart()
							set_fish_functions()
							save_log_file()
							set_owner()  # This function set home folder permissions - need to be the last one
							print(CASE_5[10].replace('#','\n'))
							with term.cbreak(), term.hidden_cursor():
								key = term.inkey()
							STEP+=1
						else:
							STEP-=2
					case _:
						break
		except KeyboardInterrupt:
			print('')
			exit(0)

if __name__ == "__main__":
    main()
